"use client";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { FormEvent,useState } from "react";
import { api } from "@/lib/api";
import { Badge,EmptyState,ErrorBox,Loading,PageHeader } from "@/components/ui";
type Service={id:string;name:string;description:string;category:string;target_roles:string[];price_range:string|null;priority:number;is_active:boolean;has_sales_profile:boolean};
const initial={name:"",description:"",category:"",target_roles:"",price_range:"",priority:50};
export default function ServicesPage(){const client=useQueryClient();const q=useQuery({queryKey:["services"],queryFn:()=>api<Service[]>("/services")});const [form,setForm]=useState(initial);const [show,setShow]=useState(false);const [error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();setError("");try{await api("/services",{method:"POST",body:JSON.stringify({name:form.name,description:form.description,category:form.category,target_industries:[],exclusions:[],geography:[],required_evidence:[],target_roles:form.target_roles.split(",").map(v=>v.trim()).filter(Boolean),business_value:[],price_range:form.price_range||null,priority:form.priority,is_active:true,signals:[]})});setForm(initial);setShow(false);await client.invalidateQueries({queryKey:["services"]})}catch(x){setError(x instanceof Error?x.message:"Ошибка")}}return <><PageHeader eyebrow="Каталог" title="Мои услуги" description="Сначала добавьте услугу, затем настройте её ICP, боли, сигналы и правила Solution Fit." actions={<button className="button" onClick={()=>setShow(v=>!v)}>Добавить услугу</button>}/>{show&&<form className="card stack" onSubmit={submit} style={{marginBottom:18}}><div className="form-grid"><div className="field"><label>Название</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Категория</label><input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div></div><div className="field"><label>Описание</label><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="form-grid"><div className="field"><label>Целевые роли</label><input value={form.target_roles} onChange={e=>setForm({...form,target_roles:e.target.value})}/></div><div className="field"><label>Диапазон стоимости</label><input value={form.price_range} onChange={e=>setForm({...form,price_range:e.target.value})}/></div></div>{error&&<ErrorBox message={error}/>}<button className="button">Сохранить</button></form>}{q.isLoading?<Loading/>:q.error?<ErrorBox message={q.error.message}/>:!q.data?.length?<EmptyState title="Каталог пуст" text="Добавьте реальную услугу. Готовые рекомендации не зашиты в систему."/>:<div className="grid">{q.data.map(s=><div className="card span-6" key={s.id}><div className="row between"><Badge value={s.is_active?"active":"outdated"}/><b>Приоритет {s.priority}</b></div><h3 style={{marginTop:15}}>{s.name}</h3><p className="muted">{s.category}</p><p>{s.description}</p><div className="divider"/><p className="hint">ЛПР: {s.target_roles.join(", ")||"не заданы"}<br/>Стоимость: {s.price_range||"не указана"}</p><Link className="button secondary" href={`/services/${s.id}/sales-profile`}>{s.has_sales_profile?"Изменить Sales-профиль":"Настроить ICP и сигналы"}</Link></div>)}</div>}</>}
