"use client";

import { useQuery } from "@tanstack/react-query";
import { ExternalLink } from "lucide-react";
import { useParams } from "next/navigation";
import { useState } from "react";
import { api } from "@/lib/api";
import { Badge, ErrorBox, Loading, PageHeader, Score } from "@/components/ui";

type Detail={id:string;name:string;inn:string|null;ogrn:string|null;legal_form:string|null;status:string|null;website:string|null;addresses:Array<{id:string;kind:string;full_address:string;region:string|null;city:string|null;evidence_id:string|null}>;people:Array<{id:string;full_name:string;confidence:number;confidence_reason:string;status:string;positions:Array<{raw_title:string;normalized_title:string;evidence_id:string}>;contacts:Array<{kind:string;value:string;origin:string;is_confirmed:boolean;evidence_id:string}>}>;resources:Array<{id:string;kind:string;url:string;title:string|null;confidence:number;evidence_id:string}>;scores:Array<{total:number;version:string;factors:Array<{category:string;weight:number;points:number;explanation:string;evidence_id:string|null}>}>;opportunities:Array<{id:string;service_id:string;title:string;score:number;confidence:number;priority:string;summary:string;details:Record<string,unknown>;status:string;evidence_ids:string[]}>};
const tabs=["Обзор","Оценка","Ресурсы","ЛПР","Что можно предложить"];
export default function CompanyPage(){const {id}=useParams<{id:string}>();const [tab,setTab]=useState("Обзор");const q=useQuery({queryKey:["company",id],queryFn:()=>api<Detail>(`/companies/${id}`)});if(q.isLoading)return <Loading/>;if(q.error)return <ErrorBox message={q.error.message}/>;if(!q.data)return null;const c=q.data;const score=c.scores.at(-1);return <><PageHeader eyebrow="Карточка компании" title={c.name} description={`ИНН ${c.inn??"не указан"} · ОГРН ${c.ogrn??"не указан"}`} actions={c.website?<a className="button" href={c.website} target="_blank" rel="noreferrer">Официальный сайт <ExternalLink size={16}/></a>:undefined}/><div className="tabs">{tabs.map(v=><button key={v} className={tab===v?"active":""} onClick={()=>setTab(v)}>{v}</button>)}</div>
{tab==="Обзор"&&<div className="grid"><div className="card span-8"><h3>Реквизиты</h3><div className="form-grid"><div><div className="muted">Юридическая форма</div><b>{c.legal_form??"Не указана"}</b></div><div><div className="muted">Статус</div><b>{c.status??"Не указан"}</b></div></div><div className="divider"/><h3>Адреса</h3>{c.addresses.length?c.addresses.map(a=><div key={a.id} className="card" style={{boxShadow:"none",marginTop:9}}><Badge value={a.kind}/><p>{a.full_address}</p><div className="muted">{a.city} · {a.region} · evidence {a.evidence_id}</div></div>):<p className="muted">Адреса не обнаружены.</p>}</div><div className="card span-4"><div className="eyebrow">Digital presence</div><div style={{fontSize:64,fontWeight:850,margin:"12px 0"}}>{score?<Score value={score.total}/>:"—"}</div><p className="muted">Оценка начисляется только за подтверждённые факторы. Отсутствующие данные дают 0, но не трактуются как проблема.</p></div></div>}
{tab==="Оценка"&&(!score?<div className="card muted">Сайт не исследован, оценка не рассчитана.</div>:<div className="table-wrap"><table className="table"><thead><tr><th>Фактор</th><th>Вес</th><th>Баллы</th><th>Объяснение</th><th>Доказательство</th></tr></thead><tbody>{score.factors.map((f,i)=><tr key={`${f.category}-${i}`}><td className="name">{f.category}</td><td>{f.weight}</td><td>{f.points}</td><td>{f.explanation}</td><td>{f.evidence_id?<a className="resource-link" href={`/evidence/${f.evidence_id}`}>{f.evidence_id.slice(0,8)}</a>:<span className="muted">Нет начисления</span>}</td></tr>)}</tbody></table></div>)}
{tab==="Ресурсы"&&<div className="stack"><a className="button" href={`/graph/${c.id}`}>Открыть интерактивный граф</a>{c.resources.length?c.resources.map(r=><div className="card row between" key={r.id}><div><Badge value={r.kind}/><h3 style={{margin:"10px 0 3px"}}>{r.title||r.url}</h3><div className="muted">Уверенность {r.confidence}% · evidence {r.evidence_id}</div></div><a className="button secondary" href={r.url} target="_blank" rel="noreferrer">Открыть</a></div>):<div className="card muted">Связанные ресурсы не обнаружены.</div>}</div>}
{tab==="ЛПР"&&<div className="stack">{c.people.length?c.people.map(p=><div className="card" key={p.id}><div className="row between"><h3>{p.full_name}</h3><Badge value={p.status}/></div><p>{p.positions.map(v=>v.raw_title).join(", ")}</p><div className="muted">Уверенность {p.confidence}% · {p.confidence_reason}</div>{p.contacts.map(v=><div key={v.value}>{v.value} · {v.origin}</div>)}</div>):<div className="card muted">Подтверждённые ЛПР не найдены.</div>}</div>}
{tab==="Что можно предложить"&&<div className="stack">{c.opportunities.length?c.opportunities.map(o=><div className="card opportunity" key={o.id}><div className="row between"><div><Badge value={o.priority}/><h3 style={{margin:"10px 0"}}>{o.title}</h3></div><Score value={o.score}/></div><p>{o.summary}</p><div className="muted">Уверенность {o.confidence}% · {o.evidence_ids.length} доказательств · <Badge value={o.status}/></div><details style={{marginTop:14}}><summary>Показать аргументацию</summary><pre className="code">{JSON.stringify(o.details,null,2)}</pre></details></div>):<div className="card muted">Коммерческие гипотезы не сформированы: нет активных услуг или достаточно подтверждённых фактов.</div>}</div>}
</>}
