"use client";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { useState } from "react";
import { api } from "@/lib/api";
import { Badge, EmptyState, ErrorBox, Loading, PageHeader, Score } from "@/components/ui";
type Scores={sales_opportunity_score:number;icp_fit:number;pain:number;purchase_probability:number;solution_fit:number;data_completeness:number;evidence_confidence:number;score_version:string};
type Opp={id:string;company_id:string;service_id:string;title:string;priority:string;status:string;summary:string;scores:Scores};
const dimensions:Array<[keyof Scores,string]>=[["icp_fit","ICP"],["pain","Боль"],["purchase_probability","Намерение"],["solution_fit","Fit"],["data_completeness","Данные"]];
export default function OpportunitiesPage(){const [minimum,setMinimum]=useState(0);const [status,setStatus]=useState("");const query=new URLSearchParams({min_score:String(minimum),...(status?{deal_status:status}:{})}).toString();const q=useQuery({queryKey:["opportunities",minimum,status],queryFn:()=>api<Opp[]>(`/opportunities?${query}`)});return <><PageHeader eyebrow="Sales Intelligence" title="Возможности продаж" description="Рейтинг основан на ICP, боли, свежести buying signals и соответствии услуги. Digital Presence Score в него не входит."/><div className="card filterbar"><div className="field"><label>Минимальный Sales Score: {minimum}</label><input type="range" min="0" max="100" step="5" value={minimum} onChange={e=>setMinimum(Number(e.target.value))}/></div><div className="field"><label>Статус сделки</label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Все</option><option value="needs_research">Нужно исследование</option><option value="ready_to_contact">Готово к контакту</option><option value="contacted">Связались</option><option value="qualified">Квалифицировано</option><option value="won">Выиграно</option><option value="lost">Проиграно</option></select></div></div>{q.isLoading?<Loading/>:q.error?<ErrorBox message={q.error.message}/>:!q.data?.length?<EmptyState title="Подходящих возможностей нет" text="Настройте Sales-профиль услуги и выполните исследование. Система не создаёт рекомендацию без evidence."/>:<div className="stack">{q.data.map(o=><article className="card opportunity" key={o.id}><div className="row between"><div><div className="row"><Badge value={o.priority}/><Badge value={o.status}/><span className="muted">{o.scores.score_version}</span></div><h2>{o.title}</h2></div><Score value={o.scores.sales_opportunity_score}/></div><p>{o.summary}</p><div className="score-strip">{dimensions.map(([key,label])=><div key={key}><span>{label}</span><b>{Math.round(Number(o.scores[key]))}</b></div>)}</div><div className="row between"><span className="muted">Evidence confidence {Math.round(o.scores.evidence_confidence)}%</span><Link className="button" href={`/opportunities/${o.id}`}>Открыть Deal Card</Link></div></article>)}</div>}</>}
